development:
  cloud_name: dxc1u5evw
  api_key: '677957218387247'
  api_secret: 1V136ij22eN8rgIHjUvlxgfz8C8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dxc1u5evw
  api_key: '677957218387247'
  api_secret: 1V136ij22eN8rgIHjUvlxgfz8C8
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dxc1u5evw
  api_key: '677957218387247'
  api_secret: 1V136ij22eN8rgIHjUvlxgfz8C8
  enhance_image_tag: true
  static_file_support: false


# production:
#   cloud_name: <%= ENV['CLOUDINARY_NAME'] %>
#   api_key: <%= ENV['CLOUDINARY_KEY'] %>
#   api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
#   secure: true
#   cdn_subdomain: true

# ---
# development:
#   cloud_name: dxc1u5evw
#   api_key: '677957218387247'
#   api_secret: 1V136ij22eN8rgIHjUvlxgfz8C8
#   enhance_image_tag: true
#   static_file_support: false
# production:
#   cloud_name: dxc1u5evw
#   api_key: '677957218387247'
#   api_secret: 1V136ij22eN8rgIHjUvlxgfz8C8
#   enhance_image_tag: true
#   static_file_support: true
# test:
#   cloud_name: dxc1u5evw
#   api_key: '677957218387247'
#   api_secret: 1V136ij22eN8rgIHjUvlxgfz8C8
#   enhance_image_tag: true
#   static_file_support: false
